services:
  - type: web
    name: school-financial-approval
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/backend/scripts/tor-api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
        value: 1cHwFk1bG8l__SEZC8DG853thOA5q8tLO
      - key: GOOGLE_DRIVE_CLIENT_ID
        sync: false
      - key: GOOGLE_DRIVE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_DRIVE_REFRESH_TOKEN
        sync: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
